### ISSUE TITLE
Logout Implementation In Oauth Client Application

### ISSUE THREAD

**Issue by yellapusony229** [Baeldung/spring-security-oauth#220]
Hello Team,

Excellent Post !

I am trying to implement logout for oauth2 client application and my client application is a spring boot project with no frontend UI. I want include the logout logic in one of my API. And want to expose this API to call from other modules.
I am using ADFS as my authorization server. I tried calling authorization-server logout endpoint by sending id-token-hint and post-redirect-uri and the logout is happening but still when I am trying to access my OAuth protected API's with old access token it considering as valid token.

Could you please provide some assistance on the above query.
Thanks In Advance.

**Comment by lor6** [comment]
Hi @yellapusony229  This depends on the authorization server, and whether it invalidates existing access tokens on logout or not. You'll need to check the ADFS documentation or ask the question of the ADFS team.

What you could do in your client application is also make sure the access token is deleted after calling the logout endpoint. 

Since this is not a problem with this repository, I'll close this issue.

Thanks.
