### ISSUE TITLE
Redirection to "/" instead of the requested endpoint after successful login.

### ISSUE THREAD

**Issue by Javs95** [Baeldung/spring-security-oauth#283]
Not much to say, after a successful login the auth server does not redirects to the requested endpoint, it shows "/" instead.
I've seen many differences between the tutorial and the source code, but even making both versions, got the same result.

**Comment by kwoyke** [comment]
Hi @Javs95 ,
We'll take a look into this.

**Comment by kwoyke** [comment]
Hi @Javs95,
Can you please provide a more detailed description on how to reproduce an issue? In which sub-module does the problem occur? Or at least a screen shoot would be more than welcome :)
We can't reproduce this situation.

**Comment by kwoyke** [comment]
We were unable to reproduce the issue. Probably it got fixed meanwhile.

**Comment by mpsanchis** [comment]
Hi @lor6 ,
I am quite new to contributing/commenting to open-source, so I am not sure if my last message reached someone or not. I thought this issue might be worth considering re-opening.
I am just tagging you because I saw a lot of activity from your side in this repo, but please let me know if there is a different way to proceed. 
Thank you
