### ISSUE TITLE
Client Credentials example

### ISSUE THREAD

**Issue by AzharMobeen** [Baeldung/spring-security-oauth#330]
Hi,

how can we avoid login page for machine to machine communication, any help would be appriciated. Ofcourse I wanted use custom authorization server as you already have.
[please have a look on this](https://auth0.com/blog/using-m2m-authorization/)

**Comment by ulisseslima** [comment]
Hey, @AzharMobeen.

Unfortunately, we can only help with issues that are specifically and directly related to our code - not with your own, custom application.

But, we have an article that might help you get started on what you need: https://www.baeldung.com/spring-webclient-oauth2

Also, StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.

Hope that makes sense.
