### ISSUE TITLE
How to maintain keycloak changes?

### ISSUE THREAD

**Issue by No3x** [Baeldung/spring-security-oauth#342]
When making changes to the configuration in keycloak how to export them to the json format? When I do an export (Menu > Export > Export groups and roles: y, Export clients: y) users and the jks is missing in the export. 

Can you pleas share information how these files were created in the first place?

**Comment by ulisseslima** [comment]
Hey, @No3x.

You can refer to the docs for how to export users in your realm: https://www.keycloak.org/server/importExport

The JKS file is not part of the realm and should be handled separately. You can check this article for how to create it: https://www.baeldung.com/spring-boot-https-self-signed-certificate

Unfortunately, we can only help with questions that are specifically and directly related to the article - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.

Hope it makes sense.
