### ISSUE TITLE
How to use Security6 and Oauth2 implement SSO?

### ISSUE THREAD

**Issue by zzc99655** [Baeldung/spring-security-oauth#462]
Hello blogger, I saw your article at Baeldung that is a about Security6 and Oauth2 Implement SSO article. recently,I met a problem,i has a authorizationServer and two Client.  I used Security6 and Oauth2 to Implement that.  now i want effect is  when i visit client1 , if user not login than redirect to AuthorizationServer login. that can  achieve at Security5. use the @EnableOAuth2Sso, but now it already is deprecated.  now i use Security6 ,if user not login when he visit Client1,the loginPage is Client1 path,  how to let it redirect to AuthorizationServer login  implement SSo.

**Comment by ulisseslima** [comment]
Hey @zzc99655.

Unfortunately, we can only help with questions that are specifically and directly related to the article - not with your own, custom application.

StackOverflow is a great place to ask more general questions.
That's primarily because we get a large number of questions and - while we do try to go through as much as everything and help wherever we can, we can't really get back to all of them.

Hope that makes sense.
